const emptyCV = {
  generalInfo: {
    userFirstName: "",
    userLastName: "",
    userEmail: "",
    userPhone: "",
    userLinkedIn: "",
    userGitHub: "",
  },
  education: [],
  workHistory: [],
  technicalSkills: [],
};

const demoCV = {
  generalInfo: {
    userFirstName: "Ryan",
    userLastName: "Skeels",
    userEmail: "ryan.skeels@gmail.com",
    userPhone: "666 53 71 84",
    userLinkedIn: "https://www.linkedin.com/in/ryan-skeels62/",
    userGitHub: "https://github.com/housemouse62",
  },
  education: [
    {
      id: crypto.randomUUID(),
      schoolName: "Colorado State University",
      cityName: "Ft. Collins",
      stateName: "Colorado",
      countryName: "USA",
      degreeName: "BS Forest Management",
      year: "2006",
    },
    {
      id: crypto.randomUUID(),
      schoolName: "International TEFL Academy",
      cityName: "Chicago",
      stateName: "Illinois",
      countryName: "USA",
      degreeName: "TEFL Certification",
      year: "2023",
    },
    {
      id: crypto.randomUUID(),
      schoolName: "Taronja Spanish Language School",
      cityName: "Valencia",
      stateName: "Valencia",
      countryName: "Spain",
      degreeName: "Continued Learning",
      year: "2023 - 2024",
    },
    {
      id: crypto.randomUUID(),
      schoolName: "La Pagoda Spanish Language School",
      cityName: "Valencia",
      stateName: "Valencia",
      countryName: "Spain",
      degreeName: "Continued Learning",
      year: "2024 - 2025",
    },
    {
      id: crypto.randomUUID(),
      schoolName: "Self-Driven Learning",
      cityName: "Online",
      stateName: "",
      countryName: "",
      degreeName: "Web Development",
      year: "2025 - Present",
    },
  ],
  workHistory: [
    {
      id: crypto.randomUUID(),
      positionTitle: "English Language Assistant",
      workPlaceName: "CEIP San Clemente",
      dates: "Oct 2024 - Present",
      city: "Sedaví",
      state: "Valencia",
      country: "Spain",
      duties: [
        "Support English language instruction for students K–6",
        "Collaborate with teachers and school leadership",
        "Classroom management and lesson planning",
      ],
    },
    {
      id: crypto.randomUUID(),
      positionTitle:
        "Freelance Content Designer & Visual Communications Specialist",
      workPlaceName: "Andrea Moore Arts (Projects for Special Olympics)",
      dates: " June 2024 - Present",
      city: "",
      state: "",
      country: "",
      duties: [
        "Created a cohesive icon library aligned with disability-related vocabulary and visual accessibility standards.",
        "Designed presentation materials in Canva and outlined educational slide decks focused on navigating healthcare systems for individuals with developmental disabilities and their advocates.",
        "Sourced and organized visuals for timelines showcasing public health and disability rights milestones.",
        "Wrote alt-text for images to support screen reader compatibility and ensure inclusive access to all materials.",
      ],
    },
    {
      id: crypto.randomUUID(),
      positionTitle: "English Tutor",
      workPlaceName: "Preply & LingoAce | Online",
      dates: " June 2024 - Present",
      city: "",
      state: "",
      country: "",
      duties: [
        "Deliver personalized 1-on-1 English lessons to learners of all levels in a virtual classroom setting.",
        "Plan and adapt lessons to meet individual learning goals, focusing on conversation, grammar, vocabulary, and real-world usage.",
        "Utilize interactive tools and authentic materials",
      ],
    },
    {
      id: crypto.randomUUID(),
      positionTitle: "Planned Career Break",
      workPlaceName: "Preply & LingoAce | Online",
      dates: "March 2023 - January 2024 ",
      city: "",
      state: "",
      country: "",
      duties: [
        "Transitioned ownership of Baere Brewing Company, including staff support, systems handover, and process documentation.",
        "Completed a 120-hour TEFL certification course",
        "Managed the visa application process and international relocation for family ",
        "Began immersive Spanish language learning through formal classes",
      ],
    },
    {
      id: crypto.randomUUID(),
      positionTitle: "Operating Manager  |  Owner  |  Founder",
      workPlaceName: "Baere Brewing Company",
      dates: "2012 - 2023",
      city: "Denver",
      state: "Colorado",
      country: "USA",
      duties: [
        "Co-founded and operated a successful craft brewery, overseeing both production and retail operations in compliance with local and federal regulations.",
        "Directed business development from concept to launch, including buildout planning, equipment sourcing, and installation.",
        "Led product development and brewing operations, creating original recipes and managing all aspects of brewing, packaging, and delivery.",
        "Managed financial operations, including payroll, accounting, and vendor payments, using best practices for small business bookkeeping.",
        "Developed and implemented HR policies, hiring procedures, and team management systems to support a collaborative work environment.",
        "Oversaw marketing strategy, social media, graphic design, and community engagement efforts, including a long-running Non-Profit of the Month program.",
        "Handled procurement of ingredients and materials, equipment maintenance, and facility upkeep",
      ],
    },
    {
      id: crypto.randomUUID(),
      positionTitle: "Environmental Health Investigator II",
      workPlaceName: "City of Denver Public Health & Environment",
      dates: "2012 - 2014",
      city: "Denver",
      state: "Colorado",
      country: "USA",
      duties: [
        "Conducted public health inspections for food manufacturing and retail facilities to ensure compliance with health codes.",
        "Authored inspection reports, summaries, and recommendations to support enforcement and education.",
        "Developed and delivered training programs for new staff, as well as food facility personnel.",
        "Responded to foodborne illness reports and public complaints, executing follow-up investigations and enforcing corrective actions.",
        "Led temporary closures and represented the department in legal proceedings related to public health violations.",
      ],
    },
    {
      id: crypto.randomUUID(),
      positionTitle: "Natural Resource Specialist",
      workPlaceName: "Jefferson County Open Space ",
      dates: "2008 - 2012",
      city: "Golden",
      state: "Colorado",
      country: "USA",
      duties: [
        "Designed and managed forest restoration and habitat conservation projects across public lands.",
        "Wrote detailed management plans, ecological assessments, and project reports based on field data.",
        "Collected, analyzed, and interpreted environmental data to guide resource decisions.",
        "Trained and supervised seasonal staff; led educational programming on machinery safety and environmental topics.",
        "Developed training materials and protocols for internal programs and public outreach.",
      ],
    },
  ],
  technicalSkills: [
    {
      id: crypto.randomUUID(),
      skillCategory: "Business",
      skills: [
        "Business Development & Strategy",
        "Operations & Project Management",
        "Policy & Procedure Development",
        "Communication",
        "Team Collaboration",
        "Training, Education & Staff Development",
        "Financial & Budget Management",
        "Regulatory Compliance & Risk Management",
        "Visual Communication & Graphic Design",
        "Human Resources & Payroll Administration",
      ],
    },
    {
      id: crypto.randomUUID(),
      skillCategory: "Web Development",
      skills: ["HTML", "CSS", "JavaScript", "React"],
    },
    {
      id: crypto.randomUUID(),
      skillCategory: "Languages",
      skills: ["Native English", "Spanish Level B2"],
    },
  ],
};
export { emptyCV, demoCV };
